spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkinglot
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  jackson:
    default-property-inclusion: non_null
